### ISSUE TITLE
CNN fails to load after whitelisting

### ISSUE THREAD

**Issue by samayer12** [pi-hole/pi-hole#1601]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**BUG REPORT:**

Encountered failure of CNN webpages (i.e. `cnn.com`, `money.cnn.com`) to load when accessed through a Pi-Hole network. Behavior persisted even after *.cnn.* (found in gravity.list) domains were added to whitelist.

**BUG Expected Behaviour:**
After addition to whitelist, expect CNN pages to load with all ads.

**BUG Actual Behaviour:**
After addition to whitelist, CNN pages do not load and exhibits same behavior as in BUG REPORT.

**BUG Steps to reproduce:**

-Generate gravity.list entries for cnn in them using command `cat /etc/pihole/gravity.list | grep 'cnn.com >> gravlist.txt`
-Add entries into whitelist
-Navigate to any cnn website, such as `cnn.com`
-Observe status

**Comment by dschaper** [comment]
Have you flushed out the cache on the clients and the Pi-hole?

https://discourse.pi-hole.net/t/how-do-i-flush-my-pi-hole-cache/3020

**Comment by samayer12** [comment]
Yes, ran commands `ipconfig /flushdns` on the host and `pihole restartdns` on the pihole.

**Comment by dschaper** [comment]
Can you run a `pihole -d` and get us the token so we can take a look at the configurations and see if there are any apparent issues?

**Comment by samayer12** [comment]
Done, see attached:

[pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/1145999/pihole_debug.txt)

**Comment by technicalpyro** [comment]
reading your log it appears you have whitelisted `xcnn.com` not `cnn.com`

**Comment by samayer12** [comment]
Correct, `xcnn.com` was one of the domains from `gravity.list`. I added `cnn.com` to the whitelist and flushed the DNS cache, no change.

**Comment by dschaper** [comment]
Can we get you to do a quick `pihole -d` and when directed, try to browse to one of the sites that is affected so we can trap the access in the logs? That will get us some baseline information to start digging in to the problem.

**Comment by samayer12** [comment]
No problem, I repeated the process as directed and browsed to `www.cnn.com` as well as `money.cnn.com`. Debug token is `mafbk0u5np`. I've also attached the output here: [pihole_debug.txt](https://github.com/pi-hole/pi-hole/files/1147109/pihole_debug.txt)

**Comment by dschaper** [comment]
If you take a look at the bottom block, the Pi-hole log, you'll see that queries for `cnn.com` are being forwarded. If they were intercepted you'd see lines that said the domains was resolved via `gravity.list`. So I'm not sure where the issue is coming in to play. 

Can you run `curl -IL www.cnn.com` and get us the output from that?

**Comment by samayer12** [comment]
My thoughts exactly. Here's the `curl` output:

> curl: (56) Recv failure: Connection reset by peer

On it's own, I didn't find that very useful so I also ran `curl -Il www.cnn.com --trace asciidump.txt`. Here's that output:

>== Info: Rebuilt URL to: www.cnn.com/
>== Info: Hostname was NOT found in DNS cache
>== Info:   Trying 151.101.1.67...
>== Info: Connected to www.cnn.com (151.101.1.67) port 80 (#0)
>=> Send header, 76 bytes (0x4c)
>0000: 48 45 41 44 20 2f 20 48 54 54 50 2f 31 2e 31 0d HEAD / HTTP/1.1.
>0010: 0a 55 73 65 72 2d 41 67 65 6e 74 3a 20 63 75 72 .User-Agent: cur
>0020: 6c 2f 37 2e 33 38 2e 30 0d 0a 48 6f 73 74 3a 20 l/7.38.0..Host: 
>0030: 77 77 77 2e 63 6e 6e 2e 63 6f 6d 0d 0a 41 63 63 www.cnn.com..Acc
>0040: 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a             ept: */*....
>== Info: Recv failure: Connection reset by peer
>== Info: Closing connection 0

I also removed pihole from the network, cleared browser and DNS caches, set my router to use Google's DNS server, and went to `www.cnn.com`. The same issue occured. It's worth noting that browsing to an ad-heavy site (I used `wired.com`) with uBlock origin disabled still gave me an ad-free site. Perhaps PiHole isn't to blame but I'm uncertain what caused the issue since everything worked fine before I added it to the network.

**Comment by dschaper** [comment]
Any updates on this, or is it still giving you the same errors?

**Comment by samayer12** [comment]
I still can't navigate to that domain. I assume you're unable to replicate the issue on your end?

**Comment by dschaper** [comment]
Closed for inactivity.
