### ISSUE TITLE
web interface shows invalid adlist info, database entries are correct.

### ISSUE THREAD

**Issue by jpgpi250** [pi-hole/pi-hole#5293]
### Versions
  Pi-hole version is v5.17 (Latest: v5.17)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform
Raspbian latest version (may 2023)
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

Raspberry Pi 3B

### Expected behavior

web interface / adlist / click on details (?) -> info displayed

### Actual behavior / bug

incorrect / contradicting information

### Steps to reproduce

pihole -g
check web interface

## Debug Token

https://tricorder.pi-hole.net/OpAGrrp5/

### Screenshots

![image](https://github.com/pi-hole/pi-hole/assets/24669386/7fa47a21-fd5a-4615-86b9-6aef4830358a)

![image](https://github.com/pi-hole/pi-hole/assets/24669386/aa6e7866-2c4b-4d70-83c8-34b5d68bb6d5)

**Comment by rdwebdesign** [comment]
I just run Gravity on my Pi-hole and I couldn't replicate the issue:
![image](https://github.com/pi-hole/pi-hole/assets/1385443/f70578c9-2c8e-4c1b-86a9-0d0f7ced3604)

Please, try to reload the page to make sure this isn't a browser cache issue.

**Comment by jpgpi250** [comment]
Microsoft Edge -> cleared cache -> same result
Firefox, runs without cache -> same result

don't know this is related, but I run gravity with _GRAVITY_TMPDIR=/home/pi/tmp_, which is a TMPFS, mount before gravity, umount after gravity.

**Comment by rdwebdesign** [comment]
> don't know this is related, but I run gravity with GRAVITY_TMPDIR=/home/pi/tmp, which is a TMPFS, mount before gravity, umount after gravity.

No.
We found the issue and it was already fixed (in development).

**Comment by jpgpi250** [comment]
copied gravity.sh from https://github.com/pi-hole/pi-hole/pull/5294 over existing /opt/pihole/gravity.sh

web interface looks OK

HOWEVER

in the pihole-FTL log, the following appears:
```
[2023-05-30 19:05:15.092 2976/T3001] SQLite3 message: file renamed while open: /etc/pihole/gravity.db (28)
[2023-05-30 19:05:15.095 2976/T3001] gravityDB_count(SELECT value FROM info WHERE property = 'gravity_count';) - SQL error step no more rows available
[2023-05-30 19:05:15.096 2976/T3001] Count of gravity domains not available. Please run pihole -g
[2023-05-30 19:05:15.186 2976/T3001] Compiled 11 whitelist and 88 blacklist regex filters for 28 clients in 89.7 msec
[2023-05-30 19:05:15.187 2976/T3001] Blocking status is enabled
[2023-05-30 19:10:00.109 2976/T3001] Notice: Database size is 4.02 MB, deleted 17 rows
[2023-05-30 19:16:14.789 2976M] Reloading DNS cache
[2023-05-30 19:16:14.815 2976/T3001] SQLite3 message: file renamed while open: /etc/pihole/gravity.db (28)
[2023-05-30 19:16:14.918 2976/T3001] Compiled 11 whitelist and 88 blacklist regex filters for 28 clients in 97.1 msec
[2023-05-30 19:16:14.919 2976/T3001] Blocking status is enabled
```

**Comment by DL6ER** [comment]
The error might have been a spurious one happening at the exact time of the swapping (it happened 3 milliseconds later, maybe we should add a delay here to ensure the process is finished, see below). This might have been a coincidence and is nothing to worry about.

You still have the old database after running `pihole -g` for the second time, what is the output of
```
pihole-FTL sql -h /etc/pihole/gravity_old.db "SELECT value FROM info WHERE property = 'gravity_count';"
```

If this returns an error, we should be concerned and check this.

**Comment by jpgpi250** [comment]
cosmetic

the output of pihole -g has an additional (unnecessary) line feed when there are "none-domains" listed

```
  [i] Target: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  [✓] Status: Retrieval successful
  [✓] Parsed 186360 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "0.0.0.0"

  [i] List stayed unchanged
```

**Comment by jpgpi250** [comment]
4th run -> 
- web interface OK
- no errors in pihole-FTL log

will report back if log error appears again
