### ISSUE TITLE
bash: line 239: /etc/pihole/piholeIP: Permission denied

### ISSUE THREAD

**Issue by BCITMike** [pi-hole/pi-hole#550]
Fresh install of Jessie Lite.

The command at the top of the page does not mention needing sudo.  But I'm guessing it should? though I see it will...

When running the script, I noticed:

```
pi@raspberrypi:~ $ curl -L https://install.pi-hole.net | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25331  100 25331    0     0  36295      0 --:--:-- --:--:-- --:--:--  101k
:::
::: sudo will be used for the install.
::: Using interface: eth0
**bash: line 239: /etc/pihole/piholeIP: Permission denied**
::: Using IPv4 on 192.168.0.50/24
::: IPv6 will NOT be used.
::: Using OpenDNS servers.
:::

```

/etc/pihole/piholeIP doesn't exist afterwards.

If I manually run the commands, it works:

```
pi@raspberrypi:/etc/pihole $ IPv4dev=$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++)if($i~/dev/)print $(i+1)}')
pi@raspberrypi:/etc/pihole $ IPv4addr=$(ip -o -f inet addr show dev "$IPv4dev" | awk '{print $4}' | awk 'END {print}')
pi@raspberrypi:/etc/pihole $ echo "${IPv4addr%/*}"
192.168.0.50
pi@raspberrypi:/etc/pihole $ echo "${IPv4addr%/*}" > /etc/pihole/piholeIP

```

**Comment by dschaper** [comment]
Thanks for the report, this is a known bug and fixed in the next release. It should be fixed in the development release, I'd need to check to see if that fix has been merged. But it shouldn't affect the operation of the Pi-Hole, there's already checks built in to the code to detect that in the released version. It's really just cosmetic for now.

**Comment by PromoFaux** [comment]
Closing as it will be fixed in next release.

**Comment by mikeo999** [comment]
Totday i start with Pi-Hole and with a clean image and same error.
```
curl -L install.pi-hole.net | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31148  100 31148    0     0  96053      0 --:--:-- --:--:-- --:--:-- 96053
:::
::: sudo will be used for the install.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your pi is up to date! Continuing with pi-hole installation...
:::
::: Checking installer dependencies...
:::    Checking for apt-utils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for dhcpcd5... already installed!
::: Using interface: eth0
bash: line 278: /etc/pihole/piholeIP: Permission denied
:::
::: Setting IP to 192.168.0.18/24.  You may need to restart after the install is complete.

```

**Comment by PromoFaux** [comment]
Argh! I thought we caught this in the last release!

**Comment by jacobsalmela** [comment]
Yeah, weird...

**Comment by PromoFaux** [comment]
Fixed [here](https://github.com/pi-hole/pi-hole/blame/master/automated%20install/basic-install.sh#L301)

But not [here](https://github.com/pi-hole/pi-hole/blame/master/automated%20install/basic-install.sh#L199)

**Comment by Mcat12** [comment]
Though the error is pointing to the one we fixed, not line 199...

**Comment by Fourdee** [comment]
Have you guys considered simply changing to?:
```
curl -L https://install.pi-hole.net | sudo bash
```

This would remove the need for any ```$SUDO``` in your code.
```
test@DietPi:/$ curl -L https://install.pi-hole.net | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0:::
::: You are root.
```

**Comment by Mcat12** [comment]
Sounds nice, although of course it adds more to the install command and we still don't feel great piping to bash. :+1:

**Comment by Fourdee** [comment]
@Mcat12 

Yep, true. :+1: 
Although most users who have security concerns, probably wouldn't run a bash pipe anyway. 

You could always pop this at the top of the installation code to warn users before proceeding:
```
#User is running installer via sudo bash pipe
if (( $(ps -aux | grep -ci -m1 '[s]udo bash') )); then

	read -p 'NOTICE: Our code is completely open, but piping to bash can be dangerous...... etc, press any key to continue, or, CTRL+C to abort.'

	#or 
	whiptail --title "Notice" --yesno "Warning regarding piping to bash" --defaultno --backtitle "Pi-hole" 15 60
	CHOICE=$?
	if (( $CHOICE != 0 )); then

		exit

	fi

fi

```

**Comment by PromoFaux** [comment]
@Fourdee That's not a bad shout, actually.

We could flesh the message out a bit along the lines of "Whilst every effort has been made to make sure this script is non-malicious, if you are uncomfortable with piping to bash, then alternatively do...<alt instructions>"

**Comment by colindean** [comment]
Just got this now on a fresh install on top of the May build of Jessie full.

    bash: line 276: /etc/pihole/piholeIP: Permission denied

**Comment by PromoFaux** [comment]
That's interesting. the `${SUDO}` variable should have populated, and then run that command as `sudo`.

Does it do the same if you run the update script? `pihole -up`?

I've been rethinking that today, anyway. As the IP is actually written out to `/etc/pihole/setupVars.conf` there isn't really any need for `/etc/pihole/piholeIP` any more, as we could just `source /etc/pihole/setupVars.conf` in `gravity.sh`

**Comment by colindean** [comment]
Just ran `pihole -up`:

```
pi@pihole:~ $ pihole -up
::: Fetching latest changes from Github...
Already up-to-date.
:::
::: You are root.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 69 updates availible for your pi!
::: We recommend you run 'apt-get upgrade' after installing Pi-Hole!
:::
:::
::: Checking installer dependencies...
:::    Checking for apt-utils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for dhcpcd5... already installed!
::: Checking Pi-Hole dependencies:
:::    Checking for dnsutils... already installed!
:::    Checking for bc... already installed!
:::    Checking for dnsmasq... already installed!
:::    Checking for lighttpd... already installed!
:::    Checking for php5-common... already installed!
:::    Checking for php5-cgi... already installed!
:::    Checking for php5... already installed!
:::    Checking for git... already installed!
:::    Checking for curl... already installed!
:::    Checking for unzip... already installed!
:::    Checking for wget... already installed!
:::    Checking for sudo... already installed!
:::    Checking for netcat... already installed!
:::
::: Stopping services... done.
:::
::: Checking for existing base files...
:::    Checking /etc/.pihole is a repo... OK!
:::     Updating repo in /etc/.pihole... done!
:::
::: Checking for existing web interface...
:::    Checking /var/www/html/admin is a repo... OK!
:::     Updating repo in /var/www/html/admin... done!
:::
::: Installing scripts to /opt/pihole... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Installing configs...
:::    Existing dnsmasq.conf found... it is not a pi-hole file, leaving alone!
:::    Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf... done.
:::
::: Creating log file and changing owner to dnsmasq... already exists!
:::
::: Installing pihole custom index page... Existing page detected, not overwriting
::: Installing sudoer file... done!
:::
::: Installing latest Cron script... done!
:::
::: Preparing to run gravity.sh to refresh hosts...
::: Cleaning up previous install (preserving whitelist/blacklist)
::: Running gravity.sh
:::
::: You are root.
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Existing pihole directory found
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting adblock.gjtech.net list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... List updated, transport successful!
::: Getting sysctl.org list... List updated, transport successful!
::: Getting zeustracker.abuse.ch list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting s3.amazonaws.com list... List updated, transport successful!
::: Getting hosts-file.net list... List updated, transport successful!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting ransomwaretracker.abuse.ch list... List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 120747 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 96796 unique domains trapped in the event horizon.
::: Formatting domains into a HOSTS file...
:::
::: Adding 10 adlist sources to the whitelist... done!
::: Running whitelist script to update HOSTS file.... 8 domains whitelisted!
::: Running blacklist script to update HOSTS file.... 0 domains blacklisted!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: Configuring iptables for httpd and dnsmasq..
::: Restarting services...Synchronizing state for dnsmasq.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d dnsmasq defaults
Executing /usr/sbin/update-rc.d dnsmasq enable
Synchronizing state for lighttpd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d lighttpd defaults
Executing /usr/sbin/update-rc.d lighttpd enable
 done.
:::
::: Update complete!
:::
::: The install log is located at: /etc/pihole/install.log
::: View the web interface at http://pi.hole/admin or http://10.9.9.2/admin
```

Didn't seem to have a problem.

**Comment by dschaper** [comment]
Resolved.
