### ISSUE TITLE
Teleporter does not restore all items needed to create duplicate pihole config

### ISSUE THREAD

**Issue by dkwolfe4** [pi-hole/pi-hole#5890]
### Versions
  Pi-hole version is v5.18.4 (Latest: v5.18.4)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)

### Platform
  OS and version:  DietPi v9.10.0 (Debian 12 based)
  Platform:  Orange Pi Zero 3

### Expected behavior

  Use of Teleporter should restore ALL items necessary to recreate pihole instance on new machine.

### Actual behavior / bug

Teleporter does not copy over items in Pi-hole FTL config file.  Specifically, it did not copy over "BLOCK_ICLOUD_PR=false" line item in the config file.  Net result is that it caused me several hours to figure out what the difference was between the new and old pihole instances... especially since I set up original pihole nearly 3 years ago and don't remember all the installation details...  eg it just works. :-)

### Steps to reproduce

1. create a teleporter file on original pihole machine that has extra lines in config file
2. install pihole on new machine
3. import teleporter file into new pihole
4. pull hair out for several hours trying to figure out what the differences are between the two instances since there's nothing in the GUI or debug reports to show that the config files are different...

Note: bug was written only to ensure that teleporter does what it's supposed to do which is to fully mirror an existing pihole instance on a new machine.  It's my understanding that v6.0 does away with the FTL config file and if so, this bug is irrelevant....

**Comment by yubiuser** [comment]
As you said, the issue is fixed in v6, but nevertheless interesting. As `pihole-FTL.conf` should be copied 1:1 it's strange that this setting is not present after importing.

**Comment by rdwebdesign** [comment]
Is this a recent backup or an old backup file?
Are you 100% sure the option `BLOCK_ICLOUD_PR=false` is present in the Teleporter file? 

I'm just asking because you said:

> ... especially since I set up original pihole nearly 3 years ago and don't remember all the installation details.

**Comment by dkwolfe4** [comment]
recent... to the point where I created the Teleport file on the old SBC (Odroid N2+) immediately before installing the new SBC (Orange Pi Zero 3).  I know this because I didn't realize that there was a "teleport" feature and had been putting off switching pi-hole to a lower powered SBC for a very long time... I don't still have the original teleport file, but I tried creating a new one using the new SBC and it does contain the "BLOCK_ICLOUD_PR=false" line... not sure what more can be done... Feel free to close if you don't think there's an issue...

**Comment by rdwebdesign** [comment]
Thanks for the answer.
I was just making sure is wasn't a misunderstanding.

> Feel free to close if you don't think there's an issue...

To be honest I didn't had the time to try to replicate your issue. We are currently focused in v6.

We can keep the issue open, to see if there are other users facing a similar problem (specially in v6), but as you know, v6 has a completely different set of config files and this issue is probably not happening.

**Comment by dkwolfe4** [comment]
If it were me, I'd close it and focus on v6....  it can always be reopened if there are other instances of it happening.
