### ISSUE TITLE
api.sh: line 25: utilsfile: readonly variable

### ISSUE THREAD

**Issue by jacklul** [pi-hole/pi-hole#6259]
### Versions

(latest develop)
- Pi-hole:  [cad0d0bf](https://github.com/pi-hole/pi-hole/commit/cad0d0bf1fbb825587d3089c273ee1a858bf5570)
- Web:  [abd4d9d3](https://github.com/pi-hole/web/commit/abd4d9d3b9554e4f08ec9bfbf69b1927b92676f3)
- FTL:  [bc24e856](https://github.com/pi-hole/FTL/commit/bc24e856fbb806087b2093ab4a34291f7f41bda4)

### Platform
- OS and version:  N/A
- Platform:  Router `Linux RT-AX58U 4.19.183 #1 SMP PREEMPT Thu Apr 17 12:22:51 CST 2025 armv7l`
- Bash: 5.2.32

### Expected behavior

No error message is shown

### Actual behavior / bug

Executing `pihole api ...` causes this error to appear: `api.sh: line 25: utilsfile: readonly variable`
`utilsfile` variable is already defined in `pihole` script
`pihole` script sources `api.sh` and then calls functions from it, `TestAPIAvailability` function redefines this variable

### Steps to reproduce

N/A

## Debug Token

- URL:  N/A

### Screenshots

N/A

### Additional context

N/A

**Comment by dschaper** [comment]
Or we declare `utilsfile` in `pihole`
https://github.com/pi-hole/pi-hole/blob/4fed49c5e5d54a19400cbb3236f2f565e2944037/pihole#L23

And then try to redeclare it in `api.sh` which is called by `pihole` and thus is already declared and `readonly` will fail.
https://github.com/pi-hole/pi-hole/blob/4fed49c5e5d54a19400cbb3236f2f565e2944037/advanced/Scripts/api.sh#L25

Seems like the `api.sh` should declare the `utilsfile` as a local variable.

**Comment by jacklul** [comment]
I believe `api.sh` can be sourced in user script without sourcing anything else right now, so moving that variable to `pihole` script would break this.

I don't think declaring it as local works:

```sh
TestAPIAvailability() {

    local chaos_api_list authResponse authStatus authData apiAvailable DNSport utilsfile

    # as we are running locally, we can get the port value from FTL directly
    readonly utilsfile="${PI_HOLE_SCRIPT_DIR}/utils.sh"
    # shellcheck source=./advanced/Scripts/utils.sh
    . "${utilsfile}"
```

```bash
$ pihole api
/opt/share/pihole/api.sh: line 22: local: utilsfile: readonly variable
/opt/share/pihole/api.sh: line 25: utilsfile: readonly variable
Status: 404

```

I would just slap a check before defining it in `TestAPIAvailability`:

```sh
[ -z "${utilsfile}" ] && readonly utilsfile="${PI_HOLE_SCRIPT_DIR}/utils.sh"
```

**Comment by jacklul** [comment]
> I believe `api.sh` can be sourced in user script without sourcing anything else right now, so moving that variable to `pihole` script would break this

Actually I'm wrong, it won't work without `PI_HOLE_SCRIPT_DIR`.

**Comment by dschaper** [comment]
The underlying issue was fixed by reverting the changes but this issue thread has some good suggestions for the next attempt at this update.

**Comment by jacklul** [comment]
> The underlying issue was fixed by reverting the changes but this issue thread has some good suggestions for the next attempt at this update.

I don't think it is:
https://github.com/pi-hole/pi-hole/blob/master/pihole#L23
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/api.sh#L25

`pihole api`: apiFunc -> LoginAPI -> TestAPIAvailability

I've updated to latest development changes on [my project](https://github.com/jacklul/entware-pi-hole) that I use to run Pi-hole on my router and the same error is still there.

---

Right now almost every script includes what they need at the top, a lot of same code duplicated.

Idea: `includes.sh`
```sh
#!/usr/bin/env bash

[ -z "${PI_HOLE_SCRIPT_DIR}" ] && exit 1 # error message or just return here

include_utils() {
    if [ -z "${included_utilsfile}" ]; then
        readonly included_utilsfile="${PI_HOLE_SCRIPT_DIR}/utils.sh"
        # shellcheck source="./advanced/Scripts/utils.sh"
        source "${included_utilsfile}"
    fi
}

# more functions for other scripts
```

So other scripts could use this like this:
```sh
readonly PI_HOLE_SCRIPT_DIR="/opt/pihole"
readonly includes="${PI_HOLE_SCRIPT_DIR}/includes.sh"
# shellcheck source="./advanced/Scripts/includes.sh"
source "${includes}"

include_COL_TABLE
include_utils
include_api
```

**Comment by warmup72** [comment]
On my raspberry the problem ist still there.
After the update

```
pihole reloaddns
  [i] FTL is not running
root@raspy:~# pihole
pihole      pihole-FTL  
root@raspy:~# pihole-FTL 
FTL started!
root@raspy:~# pihole reloaddns
  [✓] Flushing DNS cache
root@raspy:~# pihole enable
/opt/pihole/api.sh: line 25: utilsfile: readonly variable
Communication error. Is FTL running?
root@raspy:~# pihole status
  [✓] FTL is listening on port 53
     [✓] UDP (IPv4)
     [✓] TCP (IPv4)
     [✓] UDP (IPv6)
     [✓] TCP (IPv6)

  [✓] Pi-hole blocking is enabled
root@raspy:~# pihole status
  [✗] DNS service is NOT running
```
Pihole stops working after some seconds

**Comment by jacklul** [comment]
> On my raspberry the problem ist still there. After the update

This might be FTL crashing issue, see https://github.com/pi-hole/FTL/issues/2473

https://discourse.pi-hole.net/t/psa-ftl-v6-2-ftl-v6-2-1-crashes-workaround/80339/1

**Comment by warmup72** [comment]
yes maybe - but the mentioned error
/opt/pihole/api.sh: line 25: utilsfile: readonly variable
is also there?

**Comment by jacklul** [comment]
The mentioned error affects scripts using API queries only, it shouldn't affect FTL daemon at all.
Check FTL log for crash notice.

**Comment by warmup72** [comment]
Is there a safe way to return to the version 6.0.6?

**Comment by jacklul** [comment]
> Is there a safe way to return to the version 6.0.6?

Developers provided a way to go back to v6.1: https://discourse.pi-hole.net/t/psa-ftl-v6-2-ftl-v6-2-1-crashes-workaround/80339/1

This is getting a bit off-topic here.

**Comment by dschaper** [comment]
@warmup72 You're not on the latest code then. You haven't shown what versions you are running but I'm fairly confident you're not on the latest. 

The FTL crashing is not related to this issue.

**Comment by warmup72** [comment]
The whole thing happened after my Pihole update today - since it is a productive system I had to import a backup and am back on the 5 :-(

**Comment by dschaper** [comment]
You still haven't provided anything for me to even begin to investigate. Please open a new thread, this is not the thread you need to be commenting on.

**Comment by jacklul** [comment]
This issue is still happening in development branch

**Comment by dschaper** [comment]
Yep.

**Comment by jacklul** [comment]
Latest release changes:

```sh
$ pihole api dns/blocking
/opt/pihole/api.sh: line 25: PI_HOLE_SCRIPT_DIR: readonly variable
$ 
```

Now `pihole api` does not return usual output at all making commands like `pihole enable` not working.
`pihole -q` seems to work.

**Comment by PromoFaux** [comment]
@jacklul should be fixed with v6.1.4

**Comment by jacklul** [comment]
> [@jacklul](https://github.com/jacklul) should be fixed with v6.1.4

Yes it is!

**Comment by SkyLined** [comment]
I am getting this error with v6.1.4:
```
root@raspberrypi:~# pihole deny x
/opt/pihole/api.sh: line 25: PI_HOLE_SCRIPT_DIR: readonly variable
```
Looking at `/usr/local/bin/pihole`, I do *not* see a readonly definition for PI_HOLE_SCRIPT_DIR:
```
root@raspberrypi:~# cat /usr/local/bin/pihole | grep -n readonly
14:# PI_HOLE_BIN_DIR is not readonly here because in some functions (checkout),
16:# error due to modifying a readonly variable.
19:readonly colfile="${PI_HOLE_SCRIPT_DIR}/COL_TABLE"
28:readonly apifile="${PI_HOLE_SCRIPT_DIR}/api.sh"
44:        readonly PASSWORD="$2"
45:        readonly CONFIRM="${PASSWORD}"
393:  readonly LOGFILE
```

This issue does seem to prevent me from adding things to the deny list. It seems that the original fix somehow didn't fully address the issue, please reopen.

**Comment by SkyLined** [comment]
I think I found the root cause: `/usr/local/bin/pihole` calls `/opt/pihole/list.sh`, which still defines the variable read-only:
```
root@raspberrypi:~# cat /opt/pihole/list.sh | grep -n readonly
12:readonly PI_HOLE_SCRIPT_DIR="/opt/pihole"
13:readonly utilsfile="${PI_HOLE_SCRIPT_DIR}/utils.sh"
17:readonly apifile="${PI_HOLE_SCRIPT_DIR}/api.sh"
```

**Comment by SkyLined** [comment]
There are other places in the code where this variable is defined read-only. This search might help you find and fix this issue in all scripts:
https://github.com/search?q=repo%3Api-hole%2Fpi-hole%20readonly%20PI_HOLE_SCRIPT_DIR&type=code

**Comment by SkyLined** [comment]
Tested locally, removing "readonly" completely from pihole, list.sh, and api.sh for both `PI_HOLE_SCRIPT_DIR` and `utilsfile` seems to fix this.

**Comment by PromoFaux** [comment]
Yeah, this is already known - and has been discussed in a couple of places, but planned for `development` once #6333 has landed

https://github.com/pi-hole/pi-hole/pull/6333#issuecomment-3071232302
