### ISSUE TITLE
Conditional FOrward Lookup in /etc/dnsmasq.d/xxx.conf not working with FTL 6.2.1

### ISSUE THREAD

**Issue by DennYoDeluxe** [pi-hole/pi-hole#6279]
### Versions

Core version is v6.1.1 (Latest: v6.1.1)
Web version is v6.2.1 (Latest: v6.2.1)
FTL version is v6.2.1 (Latest: v6.2.1)

### Platform

- OS and version:  Linux PiHole2 6.1.0-31-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.128-1 (2025-02-07) x86_64 GNU/Linux

- Platform:  VM on Proxmox/QEMU

### Expected behavior
pihole.toml:
etc_dnsmasq_d = true

/etc/dnsmasq.d/custom.conf:
server=/home.local/192.168.11.250
rev-server=192.168.11.0/24,192.168.11.250

Expected Forward:
---------------------
nslookup test.home.local pi.hole

Name: test.home.local
Address: 192.168.11.1

Expected Reverse:
----------------------
nslookup 192.168.11.1 pi.hole

Name: test.home.local
Address: 192.168.11.1

### Actual behavior / bug

Expected Forward:
nslookup test.home.local pi.hole

*** pve3.home.local.home.local was not found by pi.hole: Non-existent domain.

Expected Reverse:
nslookup 192.168.11.1 pi.hole

Name: test.home.local
Address: 192.168.11.1

In conclusion:
With FTL 6.2.1 Reverse Lookups work, but conditional forward Lookups don't work.

I also tried to fill UI "Conditional Forward" with:
true,192.168.11.0/24,192.168.11.250,home.local

That causes also Reverse Lookups to work but not conditioned Forward Lookups.

## Debug Token

- URL:  https://tricorder.pi-hole.net/7JfsNSp7/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I used to have a custom.conf unter /etc/dnsmasq.d/ to forward specific internal Domains to another DNS Server (my Active DIrectory) which holds DHCP Entries and some A Records for internal Systems.

All Versions before 6.2.1 worked and all requests for *.home.local were forwarded to my MS DNS Server 192.168.11.250. 

With 6.2.1 it does not work anymore, only reverse is working, forward is not possible in any way.

**Comment by TheNec** [comment]
> pihole.toml: etc_dnsmasq_d = true

I think you checked your current 'pihole.toml' against that?

As a workaround you may try the following:

- Open the Pi-hole webinterface
- Goto 'Settings' - 'All Settings' - 'DNS Server' - 'dns.revServers'
- Clear 'Values'
- Click [X Save & Apply]
- Goto 'Settings' - 'All Settings' - 'Miscellaneous'
- Uncheck 'misc.etc_dnsmasq_d' - '[ ] Enabled'
- Next to it you'll find 'misc.dnsmasq_lines'
- READ!
- Enter your custom 'server=' and 'rev-server=' lines at 'Values' (one item per line!)
- Click [X Save & Apply]

Please test and report back if that solves your problem (for now)

If it works then seemingly only your custom '.conf' file is not read, if not there is another problem.

**Comment by coderunner34-ahruphey** [comment]
See https://github.com/pi-hole/pi-hole/issues/6280 for a solution

**Comment by DennYoDeluxe** [comment]
> See [#6280](https://github.com/pi-hole/pi-hole/issues/6280) for a solution

Hi Coderunner,
I tested the Conditional Forwarding Entries the same way you did without Success.
https://github.com/pi-hole/pi-hole/issues/6280#issuecomment-2946182823

The Result with these Entries ist that:
Reverse Lookups: working
Forward Lookups to AD-Server: not working

Will try TheNec's Idea next.

**Comment by coderunner34-ahruphey** [comment]
Did you use the debug function from Pi-Hole

like
`
pi-hole debug
`

`
Start a debugging session
  Add '-c' or '--check-database' to include a Pi-hole database integrity check
  Add '-a' to automatically upload the log to tricorder.pi-hole.net
`

**Comment by dschaper** [comment]
nslookup **_test.home.local_** pi.hole 

versus

**_pve3.home.local.home.local_** was not found

So somewhere you have test == pve3? 

Now the duplication of the local domain is from `nslookup`. You need to use a trailing `.` or Windows will append the local domain to the query. 

`nslookup test.home.local.`

**Comment by DennYoDeluxe** [comment]
> > pihole.toml: etc_dnsmasq_d = true
> 
> I think you checked your current 'pihole.toml' against that?
> 
> As a workaround you may try the following:
> 
> * Open the Pi-hole webinterface
> * Goto 'Settings' - 'All Settings' - 'DNS Server' - 'dns.revServers'
> * Clear 'Values'
> * Click [X Save & Apply]
> * Goto 'Settings' - 'All Settings' - 'Miscellaneous'
> * Uncheck 'misc.etc_dnsmasq_d' - '[ ] Enabled'
> * Next to it you'll find 'misc.dnsmasq_lines'
> * READ!
> * Enter your custom 'server=' and 'rev-server=' lines at 'Values' (one item per line!)
> * Click [X Save & Apply]
> 
> Please test and report back if that solves your problem (for now)
> 
> If it works then seemingly only your custom '.conf' file is not read, if not there is another problem.

Hi @TheNec ,

thanks for your tipp but poorly this also does not work. I followed your instruction precisely.

The Result is nearly the same:
Forward Entries: NOT working
Reverse Entries: Working

My PiHoles IP is: 192.168.11.13
My Active Directory an MS DNS/DHCP Server has 192.168.11.250 (Upstream Server for PiHole for Resolution of *.home.local)

Core version is v6.1.2 (Latest: v6.1.2)
Web version is v6.2.1 (Latest: v6.2.1)
FTL version is v6.2.2 (Latest: v6.2.2)


Szenario 1: False Test that Resolution is not possible as expected.
----------------------------------------------------------------------------
misc.etc_dnsmasq_d = false
misc.dnsmasq_lines = empy
dns.revServers = empty

Output Forward:
nslookup pve3.home.local 192.168.11.13
Server:  pi.hole
Address:  192.168.11.13

*** pve3.home.local wurde von pi.hole nicht gefunden: Non-existent domain.

Output Reverse:
nslookup 192.168.11.197 192.168.11.13
Server:  pi.hole
Address:  192.168.11.13

*** 192.168.11.197 wurde von pi.hole nicht gefunden: Non-existent domain.

Result: expected


Szenario 2: Forward and Reverse should work
---------------------------------------------------
misc.etc_dnsmasq_d = false
misc.dnsmasq_lines = 
    rev-server=192.168.11.0/24,192.168.11.250
    server=/home.local/192.168.11.250
dns.revServers = empty

Output Forward:
nslookup pve3.home.local 192.168.11.13
Server:  pi.hole
Address:  192.168.11.13

*** pve3.home.local wurde von pi.hole nicht gefunden: Non-existent domain.

Output Reverse:
nslookup 192.168.11.197 192.168.11.13
Server:  pi.hole
Address:  192.168.11.13

Name:    pve3.home.local
Address:  192.168.11.197


Result: unexpected, Forward and Reverse should work.

----------------

I have 2 PiHoles Running, the other one is on 
Core version is v6.0.6 (Latest: v6.1.2)
Web version is v6.1 (Latest: v6.2.1)
FTL version is v6.1 (Latest: v6.2.2)

I did the exact same config on that node and everything is working. But after pihole -up everything breaks as described above.

**Comment by DennYoDeluxe** [comment]
> nslookup **_test.home.local_** pi.hole
> 
> versus
> 
> **_pve3.home.local.home.local_** was not found
> 
> So somewhere you have test == pve3?
> 
> Now the duplication of the local domain is from `nslookup`. You need to use a trailing `.` or Windows will append the local domain to the query.
> 
> `nslookup test.home.local.`

Does not make any difference. 

You found pve3.home.local.home.local in my logs cause I was testing if that makes any differences. It was not windows adding the domain again, it was myself typing that into the nslookup command :-D

**Comment by tomaspapan** [comment]
Please have a look here: https://discourse.pi-hole.net/t/etc-dnsmasq-d-config-not-loading-after-updating-to-6-1/80309

for me it was enough to set dns.domain="" and everything is working back again.

**Comment by DennYoDeluxe** [comment]
> Please have a look here: https://discourse.pi-hole.net/t/etc-dnsmasq-d-config-not-loading-after-updating-to-6-1/80309
> 
> for me it was enough to set dns.domain="" and everything is working back again.

Interesting but for me it does not solve. But emptiing the value now causes that DNS Request times out instead of non-existent domain.

nslookup pve3.home.local 192.168.11.13
Server:  pi.hole
Address:  192.168.11.13

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Zeitüberschreitung bei Anforderung an pi.hole.


This is very strage. I have had the string dns.domain = home.local

The normally NO Upstream Server should be asked except if I condifured one exactly for this domain (which I did):

_This DNS domain is purely local. FTL may answer queries from its local cache and configuration but *never* forwards any requests upstream *unless* you have configured a dns.revServer exactly for this domain. In the latter case, all queries for this domain are sent exclusively to this server (including reverse lookups)._

BUT this obviously does not match/work so that pi.hole simply sais: NXDOMAIN


After I emptied the String dns.domain = ""

_You can disable setting a domain by setting this option to an empty string._

Then I got a timeout and not an NXDOMAIN.


So I may have two layered problems and one of them is solved, but still not the fact that forward conditions are not working.

**Comment by DennYoDeluxe** [comment]
Problem solved with:

Core version is v6.1.2
Web version is v6.2.1
FTL version is v6.2.3 <-

All Seetings -> Misc -> misc.dnsmasq_lines: server & rev-server entries added
misc.etc_dnsmasq_d = disabled
dns.domain = empty

Problem exists when:
dns.domain = set to a value, in my case "home.local"

**Comment by UdoD5** [comment]
Hi, 
running on v6.2.2 an I have the same issue, local DNS requests are not forwareded to my UDMPro.  I don't think the issue is resolved. I changed the PI local domain name to something else than "lan" but it still doesn't work. Removing the domain entirely works only once. The next request ends up in a timeout (no reply)
