### ISSUE TITLE
`/opt/pihole/gravity.sh: line 49: /etc/pihole/setupVars.conf: No such file or directory`

### ISSUE THREAD

**Issue by jacobsalmela** [pi-hole/pi-hole#764]
_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be _replicated_
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
- [ ] 1 (very unfamiliar)
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [] 8
- [ ] 9
- [X] 10 (very familiar)
---

**[BUG | ISSUE] Expected Behaviour:**
`/etc/pihole/setupVars.conf` should be sourced during install

**[BUG | ISSUE] Actual Behaviour:**
The installer produces this error
`/opt/pihole/gravity.sh: line 49: /etc/pihole/setupVars.conf: No such file or directory`

`/var/log/pihole.log` also displays `bad address`, which may or may not be related, but can be fixed by running `pihole -g`.

**[BUG | ISSUE] Steps to reproduce:**  
- Run the installer.

**Comment by jacobsalmela** [comment]
This can probably be fixed [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L916-L925) or [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L842).

**Comment by Mcat12** [comment]
Although the issue is on a new install, and those two lines are only called on an update. Maybe [here](https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L950)?

**Comment by cybrnook** [comment]
Yep, sorry just opened this as a new bug.

**Comment by PromoFaux** [comment]
Fixed in 2.9.5, possibly earlier actually.

**Comment by jacobsalmela** [comment]
I think we fixed this..just have to find where

**Comment by jacobsalmela** [comment]
JINX

**Comment by PromoFaux** [comment]
> JINX

We're good at this...

**Comment by felon-efnet** [comment]
still experiencing this error on the latest Pi-hole w/ a fresh install. scratching my head atm. the /etc/pihole dir is empty except for the install.log

**Comment by Mcat12** [comment]
@felon-efnet please open a new issue with a debug log token

**Comment by notDavid** [comment]
fyi, also seeing the same error. My pi-hole automatically updated itself somewhere in the past weeks, and now i get:

```
$ pihole -g
/usr/local/bin/pihole: line 82: /opt/pihole/gravity.sh: No such file or directory
```

Also, when i browse to "http://doubleclick.net/" i see this in Safari:

> [ERROR] There are no domain lists generated lists within /etc/pihole/! Please update gravity by running pihole -g, or repair Pi-hole using pihole -r.

The ```gravity.list``` file exists, but the ```list.*.domains``` files do not exist.

**Comment by jacobsalmela** [comment]
@notDavid please make a new issue if `pihole -r` does not resolve the issue.

**Comment by L3rchal** [comment]
```
/opt/pihole/gravity.sh: line 637: /etc/pihole/list.preEventHorizon: No such file or directory
comm: /etc/pihole/list.preEventHorizon: No such file or directory
Stopping pihole-FTL
Starting pihole-FTL (no-daemon)
```

Looks like bug is still persistent.

**Comment by dschaper** [comment]
That looks like it's not related to this bug. That's a completely different file.

**Comment by cybrnook** [comment]
Yeah, it's this bug :-) :
https://github.com/pi-hole/pi-hole/issues/2465
